development:
  host: 'localhost'
  port: 6379
  password: nil
production:
  host: URI.parse(ENV["REDISTOGO_URL"]).host
  port: URI.parse(ENV["REDISTOGO_URL"]).post
  password: URI.parse(ENV["REDISTOGO_URL"]).password
